workflows:
  version: 2
  test:
    jobs:
      - test

version: 2
jobs:
  test:
    docker:
      - image: circleci/golang:1.12

    working_directory: /go/src/github.com/{{ORG_NAME}}/{{REPO_NAME}}
    steps:
      - checkout

      - run: GO111MODULE=on go test -v ./...